name: hackattic
version: 0.1.0.0
github: "githubuser/hackattic"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2021 Author name here"

extra-source-files:
  []
  # - README.md
  # - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/hackattic#readme>

dependencies:
  - aeson
  - base >= 4.7 && < 5
  - base64-bytestring
  - binary
  - bytestring
  - containers
  - data-default
  - dhall
  - extra
  - http-media
  - jose-jwt
  - protolude
  - qm-interpolated-string
  - regex-pcre
  - req
  - servant
  - servant-server
  - text
  - time
  - wai
  - wai-extra
  - wai-logger
  - warp
  - websockets
  - wuss
  - zlib

default-extensions: NoImplicitPrelude

library:
  source-dirs: src

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wpartial-fields
  - -Wredundant-constraints
  - -fhide-source-paths

executables:
  hackattic-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hackattic
    when:
      - condition: false
        other-modules: Paths_hackattic

tests:
  hackattic-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hackattic
    when:
      - condition: false
        other-modules: Paths_hackattic
